### ISSUE TITLE
Code about 'data_generator_func'

### ISSUE THREAD

**Issue by BeerTai** [fskong/LENA#2]
Hi, What does this code mean?Especially the formula 'shape=[H,L + 1,4]' for the last line. Thank you! 
https://github.com/fskong/LENA/blob/c69036b404e29855c40b250e4ec57af75c80a3e7/LENA.py#L395-L405

**Comment by SJIANAN** [comment]
> Hi, What does this code mean?Especially the formula 'shape=[H,L + 1,4]' for the last line. Thank you!
> https://github.com/fskong/LENA/blob/c69036b404e29855c40b250e4ec57af75c80a3e7/LENA.py#L395-L405
